INSERT INTO AB_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL) VALUES (1, 'Usuario 1', 'usuario1', '1234', 'usuario1@gmail.com');

INSERT INTO AB_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL) VALUES (2, 'Usuario 2', 'usuario2', '1234', 'usuario2@gmail.com');

ALTER SEQUENCE AB_USUARIO_ID_SEQ RESTART WITH 3;

INSERT INTO AB_LIVRO (ID, TITULO, AUTOR, DESCRICAO, EDITORA, LIVRO_STATUS) VALUES (1, 'Livro 1', 'Autor 1', 'Descricao 1', 'Editora 1', 'DISPONIVEL');

INSERT INTO AB_LIVRO (ID, TITULO, AUTOR, DESCRICAO, EDITORA, LIVRO_STATUS) VALUES (2, 'Livro 2', 'Autor 2', 'Descricao 2', 'Editora 2', 'DISPONIVEL');

ALTER SEQUENCE AB_LIVRO_ID_SEQ RESTART WITH 3;

INSERT INTO AB_PERFIL(ID, DESCRICAO) VALUES (1, 'Administrador');

INSERT INTO AB_PERFIL(ID, DESCRICAO) VALUES (2, 'Gerente');

INSERT INTO AB_PERFIL(ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE AB_PERFIL_ID_SEQ RESTART WITH 4;

INSERT INTO AB_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuario', 'usuario');
INSERT INTO AB_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO AB_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE AB_RECURSO_ID_SEQ RESTART WITH 4;

-- INSERT INTO AB_ALUGUEL (ID, USUARIO_ID, LIVRO_ID, DATA_ALUGUEL, DATA_DEVOLUCAO) VALUES (1, 1, 1, '2024-06-20T18:12:42.260492', null);

-- ALTER SEQUENCE AB_ALUGUEL_ID_SEQ RESTART WITH 2;
